### ISSUE TITLE
Sitemap breaks on HHVM and L4

### ISSUE THREAD

**Issue by Ortix92** [RoumenDamianoff/laravel-sitemap#68]
As the title says, this does not work on HHVM. It's very odd. It happens in the `Sitemap.php` file around line 167 when you're trying to store the sitemaps in cache. It's strange because when I store something in cache anywhere else it works fine. I use cache in different places in my app and that works fine.

This happens in both Redis and Memcached. I haven't tested any other driver.

The error including stack trace:

```php
exception 'InvalidArgumentException' with message 'Unknown setter 'date''
in /home/forge/test.animekyun.com/vendor/nesbot/carbon/src/Carbon/Carbon.php:556
Stack trace:
#0 (): Carbon\Carbon->__set()
#1 (): DateTime->__sleep()
#2 /home/forge/test.animekyun.com/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(67): serialize()
#3 /home/forge/test.animekyun.com/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(94): Illuminate\Cache\RedisStore->put()
#4 (): Illuminate\Cache\Repository->put()
#5 /home/forge/test.animekyun.com/bootstrap/compiled.php(8300): call_user_func_array()
#6 /home/forge/test.animekyun.com/bootstrap/compiled.php(3271): Illuminate\Support\Manager->__call()
#7 /home/forge/test.animekyun.com/vendor/roumen/sitemap/src/Roumen/Sitemap/Sitemap.php(169): Illuminate\Support\Facades\Facade::__callStatic()
#8 /home/forge/test.animekyun.com/vendor/roumen/sitemap/src/Roumen/Sitemap/Sitemap.php(143): Roumen\Sitemap\Sitemap->generate()
#9 /home/forge/test.animekyun.com/app/routes/sitemap.routes.php(18): Roumen\Sitemap\Sitemap->render()
#10 (): Closure$()
#11 /home/forge/test.animekyun.com/bootstrap/compiled.php(5398): call_user_func_array()
#12 /home/forge/test.animekyun.com/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run()
#13 /home/forge/test.animekyun.com/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute()
#14 /home/forge/test.animekyun.com/vendor/dingo/api/src/Routing/Router.php(205): Illuminate\Routing\Router->dispatch()
#15 /home/forge/test.animekyun.com/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch()
#16 /home/forge/test.animekyun.com/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch()
#17 /home/forge/test.animekyun.com/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle()
#18 /home/forge/test.animekyun.com/bootstrap/compiled.php(7825): Barryvdh\Debugbar\Middleware\Stack->handle()
#19 /home/forge/test.animekyun.com/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle()
#20 /home/forge/test.animekyun.com/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle()
#21 /home/forge/test.animekyun.com/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle()
#22 /home/forge/test.animekyun.com/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle()
#23 /home/forge/test.animekyun.com/public/index.php(49): Illuminate\Foundation\Application->run()
#24 {main} {"url":"http://test.animekyun.com/sitemap"} []
```

**Comment by Ortix92** [comment]
This is my current caching implementation to bypass yours in the meantime:

```php
    return Cache::remember('laravel.sitemap', 1440, function () use ($sitemap) {
        return $sitemap->render('xml');
    });
```
